/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.AgenControler;
import javax.swing.JTextField;

/**
 *
 * @author Particular
 */
public class AgendarView extends javax.swing.JFrame {
    
    private final AgenControler controler;

    /**
     * Creates new form AgendarView
     */
    public AgendarView() {
        initComponents();
        controler = new AgenControler(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAGIdCliente = new javax.swing.JTextField();
        txtAGIdServ = new javax.swing.JTextField();
        txtAGValor = new javax.swing.JTextField();
        txtAGObs = new javax.swing.JTextField();
        txtAGData = new javax.swing.JTextField();
        BCadAgen = new javax.swing.JButton();
        FundoAge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agendamento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Serviço:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Obs:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        txtAGIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAGIdClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtAGIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, -1));
        getContentPane().add(txtAGIdServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, -1));
        getContentPane().add(txtAGValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 180, -1));
        getContentPane().add(txtAGObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 180, -1));
        getContentPane().add(txtAGData, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 180, -1));

        BCadAgen.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        BCadAgen.setText("Cadastrar Agendamento");
        BCadAgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadAgenActionPerformed(evt);
            }
        });
        getContentPane().add(BCadAgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 180, -1));

        FundoAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabeca-de-corte-de-cabelo-na-barbearia-o-barbeiro-corta-o-cabelo-na-cabeca-do-cliente-o-processo-de-criacao-de-penteados-para-homens-barbearia_100894-546.jpg"))); // NOI18N
        getContentPane().add(FundoAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAGIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAGIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAGIdClienteActionPerformed

    private void BCadAgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadAgenActionPerformed
        controler.SalvarAgenda();
    }//GEN-LAST:event_BCadAgenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarView().setVisible(true);
            }
        });
    }

    public JTextField getTxtAGData() {
        return txtAGData;
    }

    public void setTxtAGData(JTextField txtAGData) {
        this.txtAGData = txtAGData;
    }

    public JTextField getTxtAGIdCliente() {
        return txtAGIdCliente;
    }

    public void setTxtAGIdCliente(JTextField txtAGIdCliente) {
        this.txtAGIdCliente = txtAGIdCliente;
    }

    public JTextField getTxtAGIdServ() {
        return txtAGIdServ;
    }

    public void setTxtAGIdServ(JTextField txtAGIdServ) {
        this.txtAGIdServ = txtAGIdServ;
    }

    public JTextField getTxtAGObs() {
        return txtAGObs;
    }

    public void setTxtAGObs(JTextField txtAGObs) {
        this.txtAGObs = txtAGObs;
    }

    public JTextField getTxtAGValor() {
        return txtAGValor;
    }

    public void setTxtAGValor(JTextField txtAGValor) {
        this.txtAGValor = txtAGValor;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCadAgen;
    private javax.swing.JLabel FundoAge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAGData;
    private javax.swing.JTextField txtAGIdCliente;
    private javax.swing.JTextField txtAGIdServ;
    private javax.swing.JTextField txtAGObs;
    private javax.swing.JTextField txtAGValor;
    // End of variables declaration//GEN-END:variables
}
