/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.CCControler;
import dao.ClienteDAO;
import dao.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.ClienteModel;

/**
 *
 * @author Particular
 */
public class CadastrarClienteView extends javax.swing.JFrame {

    private final CCControler controler;

    /**
     * Creates new form CadastrarClienteView
     */
    public CadastrarClienteView() {
        initComponents();
        controler = new CCControler(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeC = new javax.swing.JTextField();
        txtCpfC = new javax.swing.JTextField();
        txtEmailC = new javax.swing.JTextField();
        BCadC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));
        getContentPane().add(txtNomeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 180, -1));
        getContentPane().add(txtCpfC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 180, -1));
        getContentPane().add(txtEmailC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 180, -1));

        BCadC.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        BCadC.setText("Cadastrar");
        BCadC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadCActionPerformed(evt);
            }
        });
        getContentPane().add(BCadC, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 90, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/homem-barbudo-bonito-esta-ficando-raspada-pelo-cabeleireiro_7502-1626.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCadCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadCActionPerformed
      
       controler.SalvarCliente();

    }//GEN-LAST:event_BCadCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarClienteView().setVisible(true);
            }
        });
    }

    public JTextField getTxtCpfC() {
        return txtCpfC;
    }

    public void setTxtCpfC(JTextField txtCpfC) {
        this.txtCpfC = txtCpfC;
    }

    public JTextField getTxtEmailC() {
        return txtEmailC;
    }

    public void setTxtEmailC(JTextField txtEmailC) {
        this.txtEmailC = txtEmailC;
    }

    public JTextField getTxtNomeC() {
        return txtNomeC;
    }

    public void setTxtNomeC(JTextField txtNomeC) {
        this.txtNomeC = txtNomeC;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCadC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCpfC;
    private javax.swing.JTextField txtEmailC;
    private javax.swing.JTextField txtNomeC;
    // End of variables declaration//GEN-END:variables
}
