/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Particular
 */
public class MenuPView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPView
     */
    public MenuPView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BAgendar = new javax.swing.JButton();
        BCadastrarC = new javax.swing.JButton();
        BAttAgen = new javax.swing.JButton();
        BRemAgen = new javax.swing.JButton();
        BBusAgen = new javax.swing.JButton();
        Fundomenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Principal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        BAgendar.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        BAgendar.setText("Agendar");
        BAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(BAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 170, -1));

        BCadastrarC.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        BCadastrarC.setText("Cadastrar Cliente");
        BCadastrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastrarCActionPerformed(evt);
            }
        });
        getContentPane().add(BCadastrarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 170, -1));

        BAttAgen.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        BAttAgen.setText("Atualizar Agendamento");
        BAttAgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAttAgenActionPerformed(evt);
            }
        });
        getContentPane().add(BAttAgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 170, -1));

        BRemAgen.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        BRemAgen.setText("Remover Agendamento");
        BRemAgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRemAgenActionPerformed(evt);
            }
        });
        getContentPane().add(BRemAgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 170, -1));

        BBusAgen.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        BBusAgen.setText("Buscar Agendamento");
        BBusAgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBusAgenActionPerformed(evt);
            }
        });
        getContentPane().add(BBusAgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 170, -1));

        Fundomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/templos-de-barbear-de-barbear-de-homem_23-2147778756.jpg"))); // NOI18N
        getContentPane().add(Fundomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgendarActionPerformed
        AgendarView telaAgendamento = new AgendarView();
        telaAgendamento.setVisible(true);
    }//GEN-LAST:event_BAgendarActionPerformed

    private void BCadastrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastrarCActionPerformed
        CadastrarClienteView telaCadCliente = new CadastrarClienteView();
        telaCadCliente.setVisible(true);
    }//GEN-LAST:event_BCadastrarCActionPerformed

    private void BAttAgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAttAgenActionPerformed
        AtualizarAgendamentoView telaAttAgen = new AtualizarAgendamentoView();
        telaAttAgen.setVisible(true);
    }//GEN-LAST:event_BAttAgenActionPerformed

    private void BRemAgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRemAgenActionPerformed
        RemoverAgendamentoView telaRemAgen = new RemoverAgendamentoView();
        telaRemAgen.setVisible(true);
    }//GEN-LAST:event_BRemAgenActionPerformed

    private void BBusAgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBusAgenActionPerformed
        BuscarAgendamentoView telaBusAgen = new BuscarAgendamentoView();
        telaBusAgen.setVisible(true);
    }//GEN-LAST:event_BBusAgenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgendar;
    private javax.swing.JButton BAttAgen;
    private javax.swing.JButton BBusAgen;
    private javax.swing.JButton BCadastrarC;
    private javax.swing.JButton BRemAgen;
    private javax.swing.JLabel Fundomenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
